import type { SiteCopy } from "@/lib/types";

export const it: SiteCopy = {
  brand: {
    corporation: "Life Extension Corporation",
    strapline: "Un futuro scelto da te",
    system: "09:09 / SISTEMA NOMINALE",
  },
  nav: {
    home: "Home",
    plans: "Programmi",
    how: "Come funziona",
    about: "Chi siamo",
    faq: "Domande",
    enroll: "Progetta la continuità",
    language: "English",
    menu: "Menu",
  },
  common: {
    learnMore: "Scopri di più",
    begin: "Inizia la proposta",
    explorePlans: "Esplora i programmi",
    included: "Incluso",
    canon: "Programma principale",
    expanded: "Modulo esperienza",
    back: "Indietro",
    continue: "Continua",
    reset: "Azzera la sessione",
    optional: "Facoltativo",
  },
  home: {
    eyebrow: "Life Extension Corporation / New York",
    title: "La tua vita non deve finire qui.",
    intro:
      "Preserva il corpo. Continua la mente. Ritorna quando la medicina sarà pronta per te.",
    assurance: "Consulenza privata · Nessun obbligo · I dati restano con te",
    futureEyebrow: "Continuità, con cura",
    futureTitle: "Il futuro è un luogo che puoi raggiungere.",
    futureBody:
      "Life Extension unisce preservazione criogenica e continuità cognitiva progettata con attenzione. Scegli la sospensione silenziosa oppure resta presente in un sogno vivo finché il mondo sarà pronto a riaccoglierti.",
    processEyebrow: "Il protocollo LE",
    processTitle: "Un passaggio continuo, sorvegliato in ogni fase.",
    process: [
      { number: "01", title: "Preserva", body: "Trasferimento e sospensione iniziano nella finestra clinica concordata." },
      { number: "02", title: "Continua", body: "Scegli il riposo o un Lucid Dream composto dai ricordi selezionati." },
      { number: "03", title: "Risvegliati", body: "Un panel futuro valuta il ripristino quando la condizione diventa reversibile." },
    ],
    bennyEyebrow: "Caso 0001",
    bennyTitle: "Benny è tornato a casa.",
    bennyBody:
      "Il nostro primo studio completo di preservazione ha dimostrato che la continuità comincia da un monitoraggio accurato. La storia di Benny fa ancora parte di ogni orientamento LE.",
    finalTitle: "La vita, parte seconda.",
    finalBody: "Componi una proposta privata dimostrativa e scopri come potrebbe essere progettata la tua continuità.",
  },
  plans: {
    eyebrow: "Programmi e moduli",
    title: "Una promessa. Un futuro costruito intorno a te.",
    intro:
      "Ogni rapporto con LE inizia dalla Cryonic Suspension. Poi scegli come vivere l’intervallo.",
    coreTitle: "Programmi principali",
    modulesTitle: "Moduli esperienza",
    includedTitle: "Ogni rapporto LE comprende",
    includedItems: [
      { title: "Monitoraggio esperto", body: "Un panel multidisciplinare segue ogni segnale di preservazione e continuità." },
      { title: "Technical Support", body: "Una guida è disponibile nei Lucid Dream idonei ogni volta che viene richiesta." },
      { title: "Valutazione del risveglio", body: "Il ripristino viene considerato solo quando la condizione originale può essere affrontata in sicurezza." },
    ],
    note: "Ogni programma viene valutato individualmente. LE non pubblica prezzi e non accetta acquisti diretti online.",
  },
  catalogue: {
    suspension: {
      name: "Cryonic Suspension",
      eyebrow: "Protocollo fondamentale",
      summary: "Preservazione a −196 °C fino a quando il ripristino diventa possibile.",
      detail: "Un ambiente sigillato e ridondante, progettato per restare stabile attraverso blackout, eventi sismici e il passare del tempo.",
    },
    lucidDream: {
      name: "Lucid Dream",
      eyebrow: "Continuità premium",
      summary: "Un sogno vivo, senza memoria della transizione.",
      detail: "Un’esperienza cognitiva composta intorno a persone, luoghi e sensazioni che rendono la vita riconoscibilmente tua.",
    },
    memorySplice: {
      name: "Memory Splice",
      eyebrow: "Modulo continuità",
      summary: "Scegli il momento esatto da cui riparte la tua vita.",
      detail: "La transizione viene collocata dopo un ricordo selezionato, così il mattino successivo può arrivare senza interruzioni.",
    },
    dreamArchitecture: {
      name: "Dream Architecture",
      eyebrow: "Modulo esperienza",
      summary: "Definisci atmosfera, tono emotivo e linguaggio visivo del tuo mondo.",
      detail: "L’intervista di progetto mappa ambienti significativi e iconografie personali senza scrivere ogni istante.",
    },
    lifeArchive: {
      name: "Life Archive",
      eyebrow: "Modulo memoria",
      summary: "Una raccolta privata dei frammenti che ti hanno reso ciò che sei.",
      detail: "Fotografie, registrazioni e ricordi selezionati restano disponibili ai futuri team di ripristino e al modello di continuità.",
    },
  },
  how: {
    eyebrow: "La scienza dell’attesa",
    title: "La condizione di oggi non deve essere la conclusione di domani.",
    intro: "LE protegge la struttura biologica a temperature estremamente basse mentre la capacità medica raggiunge il bisogno umano.",
    steps: [
      { number: "01", title: "Pianificazione", body: "Protocollo, preferenze e contatti responsabili vengono documentati prima che siano necessari." },
      { number: "02", title: "Trasferimento clinico", body: "Dopo la morte legale, il team avvia stabilizzazione e trasporto nella finestra concordata." },
      { number: "03", title: "Ibernazione sospesa", body: "Il contenitore mantiene −196 °C con infrastrutture ridondanti e osservazione continua." },
      { number: "04", title: "Ripristino futuro", body: "Un panel stabilisce quando riparazione e risveglio raggiungono la soglia di sicurezza concordata." },
    ],
    specs: [
      { value: "−196 °C", label: "Ambiente di sospensione" },
      { value: "24 / 7", label: "Monitoraggio segnali" },
      { value: "3×", label: "Ridondanza indipendente" },
      { value: "1", label: "Identità continua" },
    ],
    lucidEyebrow: "L’intervallo, riprogettato",
    lucidTitle: "Non sonno. Una vita che continua a sembrare vita.",
    lucidBody: "Lucid Dream è il livello cognitivo facoltativo per chi preferisce la continuità alla sospensione inconscia. Splice, costanti emotive e ricordi formano il vocabolario dell’esperienza, non un copione rigido.",
  },
  about: {
    eyebrow: "Dentro LE",
    title: "Una stanza tranquilla ai confini del possibile.",
    intro: "Life Extension nasce da una convinzione semplice: una malattia risolvibile non dovrebbe diventare definitiva solo perché la soluzione arriva tardi.",
    storyTitle: "Il nostro scopo",
    storyBody: [
      "Riuniamo scienza della preservazione, design della continuità e custodia a lungo termine in un unico rapporto responsabile.",
      "I nostri spazi sono volutamente quieti. Il linguaggio è diretto. Il futuro è già abbastanza difficile da immaginare; prepararlo deve essere chiaro.",
    ],
    principlesTitle: "Le promesse che manteniamo",
    principles: [
      { title: "Continuità", body: "La tua identità è trattata come un insieme vivo, non come una raccolta di documenti." },
      { title: "Custodia", body: "La cura a lungo termine nasce da ridondanza, revisione e memoria istituzionale." },
      { title: "Scelta", body: "Decidi se l’intervallo sarà silenzioso, sognato o riconsiderato in seguito." },
    ],
  },
  faq: {
    eyebrow: "Prima di decidere",
    title: "Le domande meritano risposte senza fretta.",
    intro: "Una consulenza privata inizia solo dopo aver compreso protocollo e limiti.",
    items: [
      { question: "Cryonic Suspension promette l’immortalità?", answer: "No. LE preserva la possibilità di una cura futura; non può garantire che il ripristino abbia successo né quando sarà disponibile." },
      { question: "Che cos’è Lucid Dream?", answer: "È un programma facoltativo che costruisce un’esperienza soggettiva continua durante la sospensione, a partire da un Memory Splice selezionato." },
      { question: "Il sogno può diventare scomodo?", answer: "Il subconscio è potente e nessun sistema soggettivo è privo di rischio. Monitoraggio e Technical Support sono inclusi nelle esperienze idonee." },
      { question: "Cosa succede ai dati inseriti nel sito?", answer: "Nulla viene inviato a LE. La proposta esiste solo nella sessione del browser e il PDF viene generato sul dispositivo." },
      { question: "È un vero servizio medico?", answer: "No. È un’esperienza narrativa non commerciale realizzata da fan e ispirata a un film. Non offre servizi medici, legali o finanziari." },
    ],
  },
  enroll: {
    eyebrow: "Studio proposte private",
    title: "Progetta la tua continuità.",
    intro: "Un breve esercizio privato per comporre una proposta LE dimostrativa. Nessun dato lascia il dispositivo.",
    privateNote: "SOLO SESSIONE / CIFRATURA NON NECESSARIA / NESSUNA TRASMISSIONE",
    progress: "Avanzamento proposta",
    steps: {
      intro: "Benvenuto",
      identity: "Identità",
      preservation: "Preservazione",
      lucid: "Continuità",
      splice: "Memory Splice",
      dream: "Design del sogno",
      support: "Supporto",
      review: "Riepilogo",
    },
    introTitle: "Un futuro scelto da te comincia da una decisione ponderata.",
    introBody: "La proposta combina un protocollo di preservazione obbligatorio con moduli di continuità facoltativi. Puoi azzerare la sessione in qualsiasi momento.",
    identityTitle: "Come deve rivolgersi a te il dossier?",
    identityBody: "Il nome è facoltativo. Il codice cliente a sei cifre viene creato localmente e resta anonimo.",
    nameLabel: "Nome da visualizzare",
    namePlaceholder: "Lascia vuoto per Cliente Privato",
    preservationTitle: "Cryonic Suspension è il fondamento.",
    preservationBody: "Ogni proposta LE include stabilizzazione biologica, trasferimento in un contenitore sigillato e monitoraggio a −196 °C.",
    preservationFact: "PROTOCOLLO PRINCIPALE CONFERMATO",
    lucidTitle: "Come deve essere vissuto l’intervallo?",
    lucidBody: "Puoi attendere in sospensione silenziosa oppure continuare in un sogno vivo facoltativo.",
    preservationOnly: "Sospensione silenziosa",
    preservationOnlyBody: "Nessuna esperienza soggettiva prima della valutazione del risveglio.",
    lucidOption: "Lucid Dream",
    lucidOptionBody: "Continua da un ricordo selezionato senza percepire la transizione.",
    spliceTitle: "Scegli la cucitura nel tempo.",
    spliceBody: "Indica un momento dopo il quale dovrebbe iniziare l’esperienza. Sii breve e riconoscibile.",
    spliceLabel: "Ricordo di ancoraggio",
    splicePlaceholder: "Il mattino dopo…",
    dreamTitle: "Dai al sogno il suo primo vocabolario.",
    dreamBody: "Queste scelte guidano l’atmosfera senza scrivere ogni istante.",
    environmentLabel: "Ambiente principale",
    environments: { coast: "Costa aperta", city: "Città familiare", garden: "Giardino privato" },
    toneLabel: "Costante emotiva",
    tones: { serene: "Serena", vivid: "Vivida", familiar: "Familiare" },
    supportTitle: "Scegli le protezioni della continuità.",
    supportBody: "Il monitoraggio esperto è sempre incluso. Scegli come può apparire il Technical Support.",
    supportLabel: "Presenza del Technical Support",
    supportModes: {
      guided: { title: "Guidata", body: "Un referente riconoscibile può apparire su richiesta o quando il monitoraggio lo richiede." },
      silent: { title: "Silenziosa", body: "Il supporto resta fuori dalla percezione, salvo instabilità della continuità." },
    },
    archiveLabel: "Includi Life Archive",
    archiveBody: "Conserva una selezione di media personali per la continuità e il futuro ripristino.",
    reviewTitle: "La proposta dimostrativa è pronta.",
    reviewBody: "Verifica il protocollo. Il dossier bilingue sarà generato interamente su questo dispositivo.",
    programLabel: "Programma di continuità",
    addOnsLabel: "Moduli esperienza",
    supportSummary: "Modalità supporto",
    none: "Nessuna selezione",
    consent: "Comprendo che si tratta di un documento fittizio, dimostrativo e non vincolante, non di un contratto medico o legale.",
    download: "Scarica il dossier bilingue",
    downloading: "Composizione dossier…",
    downloaded: "Dossier scaricato. La sessione resta privata.",
    downloadError: "Impossibile generare il dossier. Riprova.",
    requiredError: "Completa la selezione per continuare.",
    techOnline: "TECH SUPPORT / MONITORAGGIO",
    specimen: "PROPOSTA DIMOSTRATIVA / NON VINCOLANTE",
  },
  footer: {
    promise: "La vita, parte seconda.",
    disclaimer: "Esperienza narrativa non commerciale realizzata da fan. Non affiliata a Paramount Pictures o a organizzazioni reali chiamate Life Extension.",
    privacy: "Nessun servizio medico · Nessuna trasmissione dati · Nessun acquisto",
  },
};
